server:
  port: 8089
  contextPath: /alumni
datasource:
  mysql:
    dsn: root:root@tcp(127.0.0.1:3306)/alumni?charset=utf8mb4&parseTime=True&loc=Local
zap:
  level: debug
email:
  host: smtp.qq.com
  port: 587
  username: 1664619620@qq.com
  password: gryokzzkzchicead
redis:
  options:
    addr: "localhost:6379"
    db: 0
jwt:
  rsa:
    privateKey: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIBOwIBAAJBAJS/Q6xhgqzycc5KEPtQrI8Bf8WakGmpum3zutno28qASP1Y0BAs
      WTEVNtrxuVXb9R3ebcrI5lYnkxR5DobffWkCAwEAAQJAdGptMJDwkSL+5xEY0ViG
      dTYbJjCeLdRk0IEdEEcrHgSvn6YRvlQ5lsSMSFxRscCO40XMq9OofPzV6RD1kWgQ
      AQIhAMXwMHC3qXmCcsxcyJ3yjCjRzSmA+PQLkijX2Z4nFQ/pAiEAwGEohnQXgdDc
      vGauBJQc3clb33s4y+Woi86WEAkUEYECIHxCWsaIJfZH9DVjEfZF68M8YiVp99+M
      3AaT6uOj+U7xAiEAk6n/8TQq1vn6dKJb8CfAAH0Oh/uNHPSq6qUniidtwAECIQCW
      cPfmrnitlRFkmV9/c5Waln9VXpj0e0sU7Zj4GqOOSg==
      -----END RSA PRIVATE KEY-----
    publicKey: |
      -----BEGIN RSA PUBLIC KEY-----
      MEgCQQCUv0OsYYKs8nHOShD7UKyPAX/FmpBpqbpt87rZ6NvKgEj9WNAQLFkxFTba
      8blV2/Ud3m3KyOZWJ5MUeQ6G331pAgMBAAE=
      -----END RSA PUBLIC KEY-----
oss:
  endpoint: https://oss-cn-chengdu.aliyuncs.com
  accessKeyId: LTAI5tDU1MgTC49kLbyA9ZCL
  accessKeySecret: WYLTdfKU39btlK7eqPiVgP7to3Nd9C
mbti:
  token: f2f5e4f97b64d936177374b176cd1d683428c11c
  api:
    sheet: https://www.jungus.cn/api/question-sheet/
    submit: https://www.jungus.cn/api/calc-results/